matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python:
        - "3.7"
      install:
        - pip install -U conan conan_package_tools bincrafters_package_tools
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - figlet
            - clang-8
      env:
        - MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"
  # Install the proper libstdc++ version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install libstdc++-7-dev -y
  # Install later CMake version
  - figlet "CMake"
  - wget https://github.com/Kitware/CMake/releases/download/v3.14.3/cmake-3.14.3-Linux-x86_64.sh
  - chmod +x cmake-3.14.3-Linux-x86_64.sh
  - sudo ./cmake-3.14.3-Linux-x86_64.sh --prefix=/usr/local/ --skip-license --exclude-subdir
  - rm cmake-3.14.3-Linux-x86_64.sh
  # Double check versions
  - cmake --version
  - $CC --version
  - $CXX --version

install:
  - conan user # creates conan data directory
  # Setup the remotes
  - figlet "Conan Remotes"
  - conan remote add rhol https://api.bintray.com/conan/rhololkeolke/public-conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
  # Configure conan profile
  - conan profile new default || echo "conan default profile already exists"
  - conan profile update settings.compiler=clang default
  - conan profile update settings.compiler.version=8 default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan profile update settings.compiler.cppstd=17 default
  - conan profile update settings.arch=x86_64 default
  - conan profile update settings.arch_build=x86_64 default
  - conan profile update settings.os=Linux default
  - conan profile update settings.os_build=Linux default
  - conan profile update settings.build_type=Release default
  - 

script:
  # Build and test
  - python build.py
  
